### PR TITLE
Add bower support

### PR DESCRIPTION
**Pull request by Globegitter**
Hey there, just saw this library and it would be great if it would have official bower support. I took the liberty of quickly creating a bower.json
I don't know if you have used bower before, but you would still need to register the package and Bower uses git Tags for versioning, so it would be great if you could add that as well.
Here are all the instructions: http://bower.io/ under Registering packages
That would be great.

### CODE REVIEW

**Comment by sishen** [comment]
Thanks @Globegitter. I have no experience on Bower but it sounds great. We'll do it!

**Comment by Globegitter** [comment]
Awesome, to be honest I haven't registered a package myself yet, but are you looking into it/are you registering? Or should I see how exactly it works from here on?

**Comment by sishen** [comment]
I'm working on it, :)

**Comment by sishen** [comment]
@Globegitter Registered for smart-time-ago. Can you verify whether it works for you or not? Thanks!

**Comment by Globegitter** [comment]
It is not on the web-repository yet, but everything else works perfectly. Thank you sishen.

**Pull request merged**
